- name: Mirror yandex repo
  copy: 
    src: files/CentOS-Base.repo 
    dest: /etc/yum.repos.d/CentOS-Base.repo

- name: epel release
  yum:
    name: epel-release

- name: Mirror yandex epel repo
  copy:
    src: files/epel.repo
    dest: /etc/yum.repos.d/epel.repo

- name: yum -y update
  yum:
    name: '*'
    state: latest
 

- name: ssh config file copy
  copy:
    src: files/sshd_config
    dest: /etc/ssh/sshd_config
- name: systemctl restart sshd
  command: systemctl restart sshd
